test comm
smarterhicomm/evaluateassertion pull request #3
Opened 2018-04-05 18:32 UTC by smarterhicomm

test code inspection

2018-04-05 18:35 UTC, amey-smarterhi approved these changes
Approved

2018-04-06 06:28 UTC, preeti-smarterhi commented on TestFile.java
>  		String test = "[7]";
Testing review comment

2018-04-06 06:33 UTC, smarterhicomm commented on TestFile.java
>  		String test = "[7]";
Ok will do that.

2018-04-06 06:33 UTC, preeti-smarterhi requested changes
PLease make changes

2018-04-06 06:35 UTC, merged